// app/src/renderer/components/AppTabs/AppTabs.tsx
import {useContext} from "react";
import {UploadsContext} from "../../context/upload";
import styles from "./AppTabs.module.css";

interface AppTabsProps {
    onTabSelected?: (tab: string) => void
}

export default function AppTabs({onTabSelected}: AppTabsProps) {
    const {
        inProgressUploadsCount,
        finishedUploadsCount,
        resetInProgressUploadsCount,
        resetFinishedUploadsCount,
    } = useContext(UploadsContext);

    const handleTabSelected = (index: string) => {
        if (typeof onTabSelected !== "undefined") {
            onTabSelected(index)
        }
    }

    return (
        <md-tabs>
            <Tab
                text="Upload files"
                icon="upload"
                onClick={() => handleTabSelected("upload")}
            />
            <Tab
                text="Uploads in progresss"
                icon="schedule"
                badge={inProgressUploadsCount}
                onClick={() => {
                    handleTabSelected("uploads-in-progress")
                    resetInProgressUploadsCount()
                }}
            />
            <Tab
                text="Finished uploads"
                icon="check_circle"
                badge={finishedUploadsCount}
                onClick={() => {
                    handleTabSelected("finished-uploads")
                    resetFinishedUploadsCount()
                }}
            />
        </md-tabs>
    );
}

interface TabsProps {
    text: string
    icon: string
    onClick: () => void
    badge?: number
}

function Tab(props: TabsProps) {
    const {text, icon, onClick} = props
    const badge = props.badge ?? 0

    return (
        <md-primary-tab onClick={onClick}>
            {badge > 0 ? (
                <span className={styles.badge}>{badge > 99 ? "99+" : badge}</span>
            ) : (
                ""
            )}
            <md-icon>{icon}</md-icon>
            {text}
        </md-primary-tab>
    );
}

// app/src/components/AppTabs.vue
<template>
  <md-tabs>
    <md-primary-tab>
        <md-icon slot="icon">upload</md-icon>
        Upload files
    </md-primary-tab>
    <md-primary-tab>
        <md-icon slot="icon">schedule</md-icon>
        Uploads in progress
    </md-primary-tab>
    <md-primary-tab>
        <md-icon slot="icon">check_circle</md-icon>
        Finished uploads
    </md-primary-tab>
  </md-tabs>
</template>

<script setup>
import { mdiTrayArrowUp } from '@mdi/js';
import { mdiClockOutline } from '@mdi/js';
import { mdiFormatListBulleted } from '@mdi/js';
</script>

<style scoped>
.tab-title {
    margin-top: 0.8em;
}
</style>
